name: Cover Letters CD

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            # sudo docker pull kultmet/cover_letters:1.1
            sudo docker stop cover_letters
            docker run --name cover_letters --rm --restart=always -d -p 80:80 kultmet/cover_letters:1.1
